language: dart
dart:
  # Install the latest stable release
  - stable

os: linux
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid-fallback
before_install:
  - git clone https://github.com/flutter/flutter.git
  - ./flutter/bin/flutter doctor
install: ./flutter/bin/flutter pub get
script: ./flutter/bin/flutter test
cache:
  directories:
    - $HOME/.pub-cache