name: jrnl
description: Mobile journal compatible with jrnl

version: 1.0.1+1

environment:
  sdk: ">=3.0.0"

module:
  androidX: true
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_markdown: ^0.6.15
  file_picker: ^5.3.2
  datetime_picker_formfield_new: ^2.1.0
  intl: ^0.18.1
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.6.3

flutter:
  uses-material-design: true

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
